### ISSUE TITLE
Inaccuracies to the Arcade PCB

### ISSUE THREAD

**Issue by Aquas77** [MiSTer-devel/Arcade-GnG_MiSTer#5]
There are some issues with the sound and some other things.

BGM vs SFX:
-The big one is that the background music isn't balanced properly to the SFX. The BGM is low in comparison.

Sound effects:
 -The stomp of the ogres in the ladders building of Stage 2 is very hissy and doesn't have the same 'thud' to it.

Gameplay issue:
-Arthur seems to be off-center to the left side when he climbs ladders by one or two pixels.
-Somehow I made Arthur go up a ladder while he was still crouched. Not sure if related to the above notation about being off-center to the left. Never saw that before...

Graphic issue:
-Arthur's icon on the overworld transition sometimes flickers as a white box instead of the icon.

Misc. Issue:
-No "rainbow flicker" occurs which is present on all GnG Arcade PCBs. It occurs pretty randomly and supposedly happens differently on every PCB and also supposedly happens more often as you get into further loops of the game, like loops 4-5 and beyond but can happen on the first loop as well.
 -One thing of note though, is that the rainbow flicker doesn't occur on any forms of emulation or other ports of the game.

Including a video that is taken direct capture from an US version Arcade PCB from YouTube for comparison: https://www.youtube.com/watch?v=bjQuOFV9xkg&t=3163s

-The rainbow flicker will be seen occasionally in this video as well.

**Comment by jotego** [comment]
Hi @Aquas77, thanks for your inputs.
The main repository for this core is actually [here](https://github.com/jotego/jt_gng). I will reply to some items here and open issues on the main repo where appropriate.

**BGM vs SFX**

![image](https://user-images.githubusercontent.com/1863036/62078724-8f6caa00-b24d-11e9-908a-8312b34a7944.png)

**Comment by jotego** [comment]
Hi @Aquas77, thanks for your inputs.
The main repository for this core is actually [here](https://github.com/jotego/jt_gng). I will reply to some items here and open issues on the main repo where appropriate.

**BGM vs SFX**

The problem is that the PCB has two sound potentiometers. One affects the whole sound and the other just the FM (i.e. BGM). The sound balance is actually arbitrary and it will depend on how it was set on your specific board. It could be made adjustable in MiST(er) so users can set it to their specific memory.

You can check the schematic here: VR2 affects BGM only and VR1 affects both BGM and SFX.

![image](https://user-images.githubusercontent.com/1863036/62078834-c17e0c00-b24d-11e9-8f7e-0e318a9e7b99.png)

**The Stomp of the Ogres**
You are totally right. I think I know how it happens. It is probably related to a different issue seen on a Megadrive game. It is easier to debug it here. I have open an issue for it [here](https://github.com/jotego/jt_gng/issues/16).

**Sprites are off by 2 pixels**
This is a bug in the latest version. You can go back one version and it should be ok. I have it in my to-do list already.

**Graphic issue**
This may be genuine to the game under those circumstances.
**Rainbow flicker**
